services:
  traveler-db:
    container_name: traveler-postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpwd
      POSTGRES_DB: traveler
    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - traveler

  traveler-pgadmin:
    container_name: traveler-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: traveler@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpwd
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - traveler-db
    networks:
      - traveler

  traveler-api:
    build: .
    container_name: traveler-api
    ports:
      - "8080:8080"
    depends_on:
      - traveler-db
    networks:
      - traveler

networks:
  traveler:
    driver: bridge

volumes:
  postgres:
  pgadmin: