version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: my-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/db
    environment:
      - POSTGRES_USER=rootuser
      - POSTGRES_PASSWORD=rootpwd
      - POSTGRES_DB=traveler
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pdadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
  api:
    build: .
    container_name: my-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: